name: FrontEnd CI Workflow

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Check Node version
        run: node -v

      - name: Install dependecies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
